### ISSUE TITLE
About requirements.txt

### ISSUE THREAD

**Issue by cv1995** [ivclab/Part-Aware_Measurement_for_3D_Pose_Estimation_and_Tracking#1]
where is the requirements.txt?

**Comment by B10532021** [comment]
Hi, sorry for late reply. 
The requirements.txt is uploaded. However, there might be some errors during "pip install -r requirements.txt". If this happens, just installl the packages one by one. Sorry for the inconvenience.

**Comment by cv1995** [comment]
> Hi, sorry for late reply.
> The requirements.txt is uploaded. However, there might be some errors during "pip install -r requirements.txt". If this happens, just installl the packages one by one. Sorry for the inconvenience.

Thank you for your reply. When I used your method to test in other scenes, I found that the performance was not very good, and some joints of the reconstructed 3D pose would be wrong. The fps of our video is 60. Here are the parameters I select.How should I adjust these parameters?
![image](https://user-images.githubusercontent.com/50230696/130925709-6dd2ed9b-a373-42f1-ac03-28c02ad2649d.png)

**Comment by B10532021** [comment]
That's possible, since these parameters play an important role in this method. You have the find the exact parameters for different dataset, for example, those thresholds for 2D-3D association and joint filters need larger number when people are closer to the cameras. Or the n_init, max_age might relate to the fps, the higher fps, the larger (according to my experience).

**Comment by cv1995** [comment]
> That's possible, since these parameters play an important role in this method. You have the find the exact parameters for different dataset, for example, those thresholds for 2D-3D association and joint filters need larger number when people are closer to the cameras. Or the n_init, max_age might relate to the fps, the higher fps, the larger (according to my experience).

What do these two parameters (n_init, max_age)  mean？How does it affect the final result?I don't know how to adjust them.Can I add your email for further communication?


> That's possible, since these parameters play an important role in this method. You have the find the exact parameters for different dataset, for example, those thresholds for 2D-3D association and joint filters need larger number when people are closer to the cameras. Or the n_init, max_age might relate to the fps, the higher fps, the larger (according to my experience).

**Comment by B10532021** [comment]
Hi, here are the concepts for these parameters, both the parameters are related to tracking:
1. n_init : it represents that the 3D skeleton must keep matching with at least a 2D pose from a camera view for n iteration after initialized, since some 3D skeletons might be accidentally formed (false positive). So if an 3D skeleton pass this constraint, we consider is as a true positive。
2. max_age: it stands for time threshold that a 3D skeleton doesn't associated to any 2D pose. So if a 3D skeleton haven't matched with any 2D pose longer than max_age. We consider the person leave the scene and delete it. 

Thus, according to my experience, the higher the dataset's fps is, both the larger values to be set. However, I can't say which values are the best. You can try different numbers and find the best combination. When I was evaluating the result, it took me a while to find them.

This is my email address: b10532021@gapps.ntust.edu.tw
Feel free to contact if you have further questions.
